### ISSUE TITLE
Výška textu v menu

### ISSUE THREAD

**Issue by kalich5** [skaut/crdm-basic#10]
Teď je to natvrdo nastavené.

Chtěli bychom mít možnost tohle normálně měnit přes nastavení šablony.

**Comment by marekdedic** [comment]
Pokud myslíš modré menu nahoře, lze upravit v customizeru.

**Comment by kalich5** [comment]
zkus si to, je to nějaké napevno. Můžu si nastavení v customizeru měnit jak chci a nic se nestane

Dělám to na tom demo webu

**Comment by marekdedic** [comment]
Nastavení šablony -> Menu -> Položky Menu -> Font Size

Upravil jsem to na demowebu a funguje to...

**Comment by kalich5** [comment]
Tam bych to fakt nehledal, tohle menu totiž v normálním GeneratePressu není. Tam se tohle nastavuje v Typografii.
