### ISSUE TITLE
odsazení nadpisu u příspěvků a ve widgetech

### ISSUE THREAD

**Issue by kalich5** [skaut/crdm-basic#11]
Aby to bylo ze všech stran stejné

**Comment by marekdedic** [comment]
Prosím o screenshot, co se má opravit.

**Comment by marekdedic** [comment]
Ok, na https://crdm-spolky-rozsirena.skauting.cz/ vidím problém, ale na lokálním WP to nenastane - je to demo updatované na poslední verzi WP a GenPress?

**Comment by marekdedic** [comment]
Lze upravit v nastavení GeneratePress - upraveno na demowebu
