### ISSUE TITLE
Obrázek u aktualit

### ISSUE THREAD

**Issue by kalich5** [skaut/crdm-basic#13]
Na úvodní stránce to vypadá docela v pohodě https://crdm-spolky-zaklad.skauting.cz/
malý obrázek

Při zobrazení celé aktuality https://crdm-spolky-zaklad.skauting.cz/2018/11/19/video-z-vyroci-crdm/ je to divný, jak ten obrázek je velký.

Chce to zmenšit na nějakých 400x400px jako na úvodní stránce. + mít možnost nastavit kde ten obrázek bude.
vlevo, vpravo, střed a nebo že se nebude vůbec zobrazovat

**Comment by marekdedic** [comment]
Nastavení velikoosti v přehledu příspěvků: https://docs.generatepress.com/article/adjusting-the-featured-images/

Udělal bych něco podobnýho, akorát nevím, kde.

**Comment by kalich5** [comment]
Tohle nastavení znám, ale to dělá jen při výpisu všeho. Neumí to při zobrazení jednoho článku, stránky...

**Comment by marekdedic** [comment]
V tuhle chvíli bych to tam dal hard-coded na prostředek s velikostí <= 400px

Až bude #77, tak bych to přidal jako plně nastavitelnou položku.

**Comment by kalich5** [comment]
velikost asi ok
A ten střed je asi zatím ok, pak by bylo dobré nastavení jako tam už je. vlevo, vpravo, střed...atd
