### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by marekdedic** [skaut/crdm-basic#38]
V tuhle chvíli je šablona napsaná v češtině, ale používá překladové funkce, kde pak na WP.org jsou jenom opsané hodnoty jako překlad do češtiny...

Navíc vložené kirki je v angličtině, takže se stejně musí překládat.

Asi by mi přišlo smysluplnější to celé ve zdrojáku hodit do angličtiny a vytvořit pro to překlad [online](https://translate.wordpress.org/locale/cs/default/wp-themes/crdm-basic/)

**Comment by kalich5** [comment]
můžeme to klidně přeházet do angličtiny a přeložit to stejně jako kirki

**Comment by marekdedic** [comment]
Nabízím pomoc s překladem, ale anglický asi umíme všichni...

**Comment by kalich5** [comment]
Super, tak to začneme postupně procházet a překládat do AJ. Aby další verze, co dáme na wp.org byla v základu anglicky. A doděláme k tomu překlad.

**Comment by marekdedic** [comment]
Překlady pro zpětné použití v překladech online

| English | Czech |
|---|---|
