### ISSUE TITLE
Security Alerts

### ISSUE THREAD

**Issue by kalich5** [skaut/crdm-basic#8]
Vyřešit Security Alerts, asi nejlépe stejně jako u toho gallery pluginu.

**Comment by marekdedic** [comment]
Ahoj,
GitHub má nově v sobě zabudovaný dependabot (koupili ho asi před měsícem), což je obdoba toho greenkeeperu, co jsem používal pro galerii. Takže když vyjde nová verze dependency, tak by to mělo samo udělat PR...

Zkouším to na té galerii, tak bych to pak kdyžtak zapnul pro všechny tyhle repozitáře.

**Comment by kalich5** [comment]
ok :-)

**Comment by kalich5** [comment]
už to asi můžeme uzavřít ne?
