### ISSUE TITLE
Add GP Premium as a dependency

### ISSUE THREAD

**Issue by marekdedic** [skaut/crdm-basic#81]
Since we will probably build upon GP Premium, we should add it as a dependency. Or Ideally make it gracefully lose features...

**Comment by kalich5** [comment]
Certainly the function must disappear. The FREE template should not depend on the PRO plugin. It can be at most as a link that the extension will add more features.

**Comment by marekdedic** [comment]
Ok, what about functionality that is currently implemented in our theme, but in GeneratePress, it's part of a Premium module? Should we remove it, so as not to clash with parent theme, or keep it or what?

**Comment by marekdedic** [comment]
GP Premium functionality will be re-implemented if premium isn't enabled. This is very few items, so it shouldn't be a problem with GP author. See #97
